name: synapses_launcher_flutter
version: 1.0.0
publish_to: "none"
description: Flutter frontend for Synapses Agentic Launcher, attachable to any backend with matching specs.
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  web_socket_channel: ^2.4.0
  # Add more as needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
